# Generated by Django 5.1.5 on 2025-02-07 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technic_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Plaka')),
                ('production_year', models.PositiveIntegerField(verbose_name='Üretim Yılı')),
                ('kilometer', models.PositiveIntegerField(default=0, verbose_name='Kilometre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic_service.servicestatus', verbose_name='Servis Durumu')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
            },
        ),
    ]
