# Generated by Django 5.1.5 on 2025-02-08 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technic_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Teknisyen'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic_service.serviceappointment', verbose_name='Randevu'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic_service.servicerecord', verbose_name='Servis Kaydı'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='service_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic_service.servicerecord', verbose_name='Servis Kaydı'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='services',
            field=models.ManyToManyField(through='technic_service.ServiceDetail', to='technic_service.servicetype', verbose_name='Yapılan İşlemler'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technic_service.servicetype', verbose_name='Hizmet Tipi'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='parts_used',
            field=models.ManyToManyField(through='technic_service.PartUsage', to='technic_service.sparepart', verbose_name='Kullanılan Parçalar'),
        ),
        migrations.AddField(
            model_name='partusage',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technic_service.sparepart', verbose_name='Yedek Parça'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technic_service.fueltype', verbose_name='Yakıt Tipi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Araç Sahibi'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technic_service.transmissiontype', verbose_name='Vites Tipi'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='compatible_models',
            field=models.ManyToManyField(related_name='spare_parts', to='technic_service.vehicle', verbose_name='Uyumlu Modeller'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic_service.vehicle', verbose_name='Araç'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technic_service.vehiclebrand', verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic_service.vehiclebrand', verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='technic_service.vehiclemodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='workflow_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technic_service.workflow', verbose_name='Durum'),
        ),
    ]
