# Generated by Django 5.1.5 on 2025-02-08 09:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technic_service', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Yakıt Tipi'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='service_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_usages', to='technic_service.servicerecord', verbose_name='Servis Kaydı'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='spare_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='technic_service.sparepart', verbose_name='Yedek Parça'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='partusage',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Birim Fiyat'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Teknisyen'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technic_service.vehicle', verbose_name='Araç'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='workflow_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='technic_service.workflow', verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ücret'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='labor_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='İşçilik Süresi'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technic_service.servicerecord', verbose_name='Servis Kaydı'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='technic_service.servicetype', verbose_name='Hizmet Tipi'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technic_service.serviceappointment', verbose_name='Randevu'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Tamamlanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='estimated_time',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Tahmini Süre (Saat)'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hizmet Adı'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Standart Ücret'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Depo Konumu'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Parça Adı'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='part_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Parça Numarası'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Alış Fiyatı'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Satış Fiyatı'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stok Miktarı'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='technic_service.vehiclebrand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Renk'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='technic_service.fueltype', verbose_name='Yakıt Tipi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometre'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='technic_service.vehiclemodel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Plaka'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='technic_service.transmissiontype', verbose_name='Vites Tipi'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Şasi No'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Model Yılı'),
        ),
        migrations.AlterField(
            model_name='vehiclebrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='vehiclebrand',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='technic_service.vehiclebrand', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model'),
        ),
    ]
