# Generated by Django 5.1.5 on 2025-02-08 08:25

import apps.userauths.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('corporation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Görev Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
            },
        ),
        migrations.CreateModel(
            name='EducationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Eğitim Alanı Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eğitim Alanı',
                'verbose_name_plural': 'Eğitim Alanları',
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Eğitim Seviyesi Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eğitim Seviyesi',
                'verbose_name_plural': 'Eğitim Seviyeleri',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cinsiyet Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cinsiyet',
                'verbose_name_plural': 'Cinsiyetler',
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Hobi Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hobi',
                'verbose_name_plural': 'Hobiler',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, unique=True, verbose_name='Meslek Adı')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meslek',
                'verbose_name_plural': 'Meslekler',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Dil Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Diller',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Uyruk Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uyruk',
                'verbose_name_plural': 'Uyruklar',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Okul Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Okul',
                'verbose_name_plural': 'Okullar',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Uzmanlık Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Uzmanlık',
                'verbose_name_plural': 'Uzmanlıklar',
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yetenek Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yetenek',
                'verbose_name_plural': 'Yetenekler',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text="User's email address.", max_length=100, unique=True, verbose_name='E-posta')),
                ('phone_number', models.CharField(help_text='Primary phone number.', max_length=15, verbose_name='Telefon Numarası')),
                ('first_name', models.CharField(help_text="User's first name.", max_length=100, verbose_name='İsim')),
                ('last_name', models.CharField(help_text="User's last name.", max_length=100, verbose_name='Soyisim')),
                ('birth_date', models.DateField(blank=True, help_text="User's birth date.", null=True, verbose_name='Doğum Tarihi')),
                ('identity_number', models.CharField(blank=True, help_text="User's identity number.", max_length=100, null=True, verbose_name='Kimlik Numarası')),
                ('passport_number', models.CharField(blank=True, help_text="User's passport number.", max_length=100, null=True, verbose_name='Pasaport Numarası')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Son eğitim yılı')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Onaylı mı?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Sahip mi?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Yönetici mi?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Personel mi?')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Müşteri mi?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kayıt Tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('place_of_work', models.ForeignKey(blank=True, help_text="User's place of work.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporation.corporation', verbose_name='Calısma Yeri')),
                ('place_of_work_unit', models.ForeignKey(blank=True, help_text="User's place of work department.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporation.unit', verbose_name='Departman')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('duty', models.ForeignKey(blank=True, help_text="User's duty.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.duty', verbose_name='Görev')),
                ('education_field', models.ForeignKey(blank=True, help_text="User's education field.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.educationfield', verbose_name='Eğitim Alanı')),
                ('education_level', models.ForeignKey(help_text="User's education level.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.educationlevel', verbose_name='Eğitim Seviyesi')),
                ('gender', models.ForeignKey(help_text="User's gender.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.gender', verbose_name='Cinsiyet')),
                ('hobbies', models.ManyToManyField(help_text="User's hobbies.", to='userauths.hobby', verbose_name='Hobiler')),
                ('job', models.ForeignKey(help_text="User's job.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.job', verbose_name='Meslek')),
                ('language', models.ForeignKey(blank=True, help_text="User's language.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.language', verbose_name='Dil')),
                ('nationality', models.ForeignKey(blank=True, help_text="User's nationnality.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.nationality', verbose_name='Uyruk')),
                ('school', models.ForeignKey(blank=True, help_text="User's school.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.school', verbose_name='Okul')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', apps.userauths.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Sokak')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eyalet')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Posta Kodu')),
                ('country', models.CharField(max_length=100, verbose_name='Ülke')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Adres',
                'verbose_name_plural': 'Adresler',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biyografi')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profil Resmi')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Web Sitesi')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Konum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profiller',
            },
        ),
        migrations.CreateModel(
            name='SchoolDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Okul Departmanı Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.school', verbose_name='Okul')),
            ],
            options={
                'verbose_name': 'Okul Departmanı',
                'verbose_name_plural': 'Okul Departmanları',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='school_department',
            field=models.ForeignKey(blank=True, help_text="User's school department.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.schooldepartment', verbose_name='Okul Departmanı'),
        ),
        migrations.CreateModel(
            name='SocialMediaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform')),
                ('url', models.URLField(verbose_name='Profil Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Sosyal Profil',
                'verbose_name_plural': 'Sosyal Profiller',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.ForeignKey(blank=True, help_text="User's speciality.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.speciality', verbose_name='Uzmanlık'),
        ),
        migrations.AddField(
            model_name='user',
            name='talents',
            field=models.ManyToManyField(help_text="User's talents.", to='userauths.talent', verbose_name='Yetenekler'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='tr', max_length=50, verbose_name='Dil Tercihi')),
                ('theme', models.CharField(default='light', max_length=50, verbose_name='Tema Tercihi')),
                ('receive_newsletter', models.BooleanField(default=True, verbose_name='Bülten Alıyor mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Tercihi',
                'verbose_name_plural': 'Kullanıcı Tercihleri',
            },
        ),
    ]
