# Generated by Django 5.1.5 on 2025-02-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text="User's birth date.", null=True, verbose_name='Doğum Tarihi'),
        ),
    ]
