# Generated by Django 5.1.5 on 2025-02-08 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Posta Kodu'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sokak'),
        ),
        migrations.AlterField(
            model_name='educationfield',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eğitim Alanı Adı'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eğitim Seviyesi Adı'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Cinsiyet Adı'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Hobi Adı'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Meslek Adı'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dil Adı'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Uyruk Adı'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Okul Adı'),
        ),
        migrations.AlterField(
            model_name='schooldepartment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Okul Departmanı Adı'),
        ),
        migrations.AlterField(
            model_name='schooldepartment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userauths.school', verbose_name='Okul'),
        ),
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Profil Linki'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yetenek Adı'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.ForeignKey(blank=True, help_text="User's education level.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.educationlevel', verbose_name='Eğitim Seviyesi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text="User's first name.", max_length=100, null=True, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(blank=True, help_text="User's gender.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.gender', verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(blank=True, help_text="User's job.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauths.job', verbose_name='Meslek'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text="User's last name.", max_length=100, null=True, verbose_name='Soyisim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Primary phone number.', max_length=15, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(blank=True, default='tr', max_length=50, null=True, verbose_name='Dil Tercihi'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='receive_newsletter',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Bülten Alıyor mu?'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(blank=True, default='light', max_length=50, null=True, verbose_name='Tema Tercihi'),
        ),
    ]
