# Generated by Django 5.1.5 on 2025-02-08 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurum Adı')),
                ('corporation_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurum Numarası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kurum',
                'verbose_name_plural': 'Kurumlar',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Birim Adı')),
                ('unit_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Birim Numarası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation', verbose_name='Kurum')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
            },
        ),
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alt Birim Adı')),
                ('sub_unit_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Alt Birim Numarası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporation.corporation', verbose_name='Kurum')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporation.unit', verbose_name='Birim')),
            ],
            options={
                'verbose_name': 'Alt Departman',
                'verbose_name_plural': 'Alt Departmanlar',
            },
        ),
    ]
